### ISSUE TITLE
Out of date vscode.d.ts

### ISSUE THREAD

**Issue by arciisine** [Microsoft/vscode-extension-vscode#105]
The `vscode.d.ts` file in the repo is missing new extension features for setting/removing breakpoints. (https://github.com/Microsoft/vscode/issues/30096).

I'm not sure what the process is for pulling the latest `vscode.d.ts` from the vscode repository itself.

**Comment by weinand** [comment]
@arciisine in your package.json set the "engines" > "vscode" attribute to the minimal version of VS Code that your extension should support. Then remove the node_modules folder and do an `npm install`. It will pull the correct version of `vscode.d.ts` from the VS Code repository.

**Comment by weinand** [comment]
What version of vscode are you specifying in your package.json?

It is the "postinstall" npm script that loads the vscode.d.ts.
You can run it manually with `npm run postinstall` (after setting the version to 1.22).

Then run the "Reload Window" command inside VS Code so that it picks up the updated node module.

You said:
> All the examples in the Vscode documentation site have vscode in the dependency section in their package.json.

Yes, sure. I tried to explain how a specific version of `vscode.d.ts` is downloaded by `npm install`. But you need to specify a recent version number, e.g. 1.22.

Using proposed API (via `vscode.proposed.d.ts`) is a different story. Let's not mix things. Your problem is an outdated version of `vscode.d.ts`.

**Comment by arciisine** [comment]
I must have misunderstood what you were indicating in the first reply (I was under the assumption you were asking me to remove the `vscode` npm module).  The post install script successfully pulled down the latest, must have missed a reload in conjunction with everything else changing.  Thanks again.

**Comment by weinand** [comment]
Glad to hear that this now works for you.
