### ISSUE TITLE
Potential security vulnerability via hoek

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode-extension-vscode#106]
See https://github.com/Microsoft/vscode-languageserver-node/network/dependencies

I get this in vscode-languageserver-node which has a dependency on vscode which then via n levels has a dependency on hoek. Do we need to update something?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/48783

**Comment by bpasero** [comment]
Actually lets close the other one as duplicate of this one.

**Comment by bpasero** [comment]
This depends on https://github.com/request/request/issues/2926 which we depend on.

**Comment by DanTup** [comment]
Based on [this comment](https://github.com/Microsoft/vscode/issues/48783#issue-318203997) it might be `gulp-remote-src` using an old version of `request` which results in an old version of `hoek`. I think the latest version of request depends on a version of `hoek` that is not vulnerable based on the comments in the related cases.

**Comment by bpasero** [comment]
@DanTup I was assuming the security issue is for any hoek version < 5, which would mean even the latest request version does not fix it?

**Comment by DanTup** [comment]
The fix was apparently ported back to the latest v4 release. Some comments at https://github.com/hapijs/hoek/issues/230#issuecomment-384805340 about it.

**Comment by DanTup** [comment]
This looks like the fix in v4.2.1: https://github.com/hapijs/hoek/blob/v4.2.1/lib/index.js#L116-L118

**Comment by DanTup** [comment]
Yeah, the CVE page still says that and I guess GH gets its data from there. Once that's fixed, I think `gulp-remote-src` will still need addressing though. I guess they'll have had an alert the same as us all though!

**Comment by bpasero** [comment]
@DanTup it looks like `gulp-remote-src` is not compatible with latest `request`, so either they need to fix it or we have to move to another library for this.

**Comment by DanTup** [comment]
Yeah. I've opened https://github.com/ddliu/gulp-remote-src/issues/16 to prompt them; though I suspect they had an alert from GH too.

**Comment by bpasero** [comment]
@DanTup thanks

**Comment by gwicksted** [comment]
Just an FYI that `hoek 4.2.1` has been deemed not vulnerable ([request comment](https://github.com/request/request/issues/2926#issuecomment-384906438)) so it looks like the request group is going with that version to keep node 4 compatibility.  Hopefully GitHub will detect that as a safe version instead of only `hoek ~> 5.0.3`.

**Comment by joaomoreno** [comment]
@egamma pinged me about this, since there are extensions out there flagging up as having a security vulnerability.

I've created a PR for gulp-remote-src: https://github.com/ddliu/gulp-remote-src/pull/17. Let's hope they take it.

Meanwhile, I've also forked it with the fix, published it to npm as `gulp-remote-src-vscode` and updated `vscode` to depend on that instead of the official. I've pushed that change to `master`, as well as a brand new `package-lock.json` file. The vulnerability is now gone from `vscode`.

If `gulp-remote-src` takes the change, we can change back our dependency to it.

@bpasero Please review and test the current `master`. If good, simply publish a new version, so extensions can start fixing their vulnerability warnings.

**Comment by bpasero** [comment]
Thanks, released `1.1.17` of vscode module.
