### ISSUE TITLE
Error installing vscode.d.ts: TypeError: Object #<Object> has no method 'map'

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode-extension-vscode#12]
Since the addition of the postinstall step I've been having Travis builds failing with this error. It occasionally happens on the Linux builds, but always on the OSX builds.

Minimum repo at [stkb/vscode-extension-test](https://github.com/stkb/vscode-extension-test) and the accompanying [Travis builds](https://travis-ci.org/stkb/vscode-extension-test). I used the template ```.travis.yml``` from https://code.visualstudio.com/docs/extensions/testing-extensions.

**Comment by DotJoshJohnson** [comment]
I encountered the same issue in my project. I submitted PR #13 as a proposed fix.

**Comment by stkb** [comment]
@DotJoshJohnson thanks :+1:

**Comment by bpasero** [comment]
Thanks much!

**Comment by bpasero** [comment]
I published vscode@0.11.2 that includes two changes. First I print an error if the result from GH is not an array of tags. Second, I allow you to provide a Github token from the environment because I believe this error results from GH throttling the calls to their API.

Please report back what you see as error printed from the test run now and if it is the throttling, you can provide a GH access token (a default one without any permissions is fine from your profile). The environment variable is called `GITHUB_TOKEN`.

**Comment by stkb** [comment]
@bpasero  The error was indeed the throttling, and using a GitHub token seems to have fixed it :+1:

**Comment by bpasero** [comment]
@stkb nice, thanks for verifying!
