### ISSUE TITLE
`node ./node_modules/vscode/bin/install` won't detect VSCode engine in ubuntu docker container

### ISSUE THREAD

**Issue by rberrelleza** [Microsoft/vscode-extension-vscode#143]
When running  `npm install`  on my extension's folder, inside an ubutu18 docker container, I get the following output:
```
npm install
npm WARN lifecycle bitbucket-pull-requests@0.3.5-dev.1~postinstall: cannot run in wd bitbucket-pull-requests@0.3.5-dev.1 node ./node_modules/vscode/bin/install
```

Running the install script directly results in the following:
```
node ./node_modules/vscode/bin/install
Error installing vscode.d.ts: Missing VSCode engine declaration in package.json.
```

My package.json looks like this:
```javascript
{
    "name": "bitbucket-pull-requests",
    "displayName": "Bitbucket Pull Requests",
    "description": "Start a bitbucket pull request from VS code",
    "version": "0.3.5-dev.1",
    "publisher": "RamiroBerrelleza",
    "icon": "assets/bitbucket.jpg",
    "license": "SEE LICENSE IN LICENSE.txt",
    "bugs": {
        "url": "https://bitbucket.org/rberrelleza/bitbucket-pull-requests/issues"
    },
    "engines": {
        "vscode": "^1.28.0"
    },
    "repository": {
        "type": "git",
        "url": "https://bitbucket.org/rberrelleza/bitbucket-pull-requests"
    },
    "categories": [
        "SCM Providers"
    ],
    "activationEvents": [
        "onCommand:extension.createPullRequest",
        "onCommand:extension.setBitbucketURL"
    ],
    "main": "./out/extension",
    "contributes": {
        "configuration": {
            "type": "object",
            "title": "Bitbucket pull requests extension configuration",
            "properties": {
                "bitbucket-pull-requests.serverURL": {
                    "type": "string",
                    "description": "Bitbucket server URL",
                    "default": "https://bitbucket.org"
                }
            }
        },
        "commands": [
            {
                "command": "extension.createPullRequest",
                "title": "Create pull request from current branch",
                "category": "Bitbucket"
            },
            {
                "command": "extension.setBitbucketURL",
                "title": "Set the Bitbucket Server URL",
                "category": "Bitbucket"
            }
        ]
    },
    "scripts": {
        "vscode:prepublish": "npm run compile",
        "compile": "tsc -p ./",
        "watch": "tsc -watch -p ./",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "npm run compile && node ./node_modules/vscode/bin/test"
    },
    "devDependencies": {
        "typescript": "^2.6.1",
        "vscode": "^1.1.22",
        "tslint": "^5.8.0",
        "@types/node": "^8.10.25",
        "@types/mocha": "^2.2.42",
        "vsce": "^1.55.0"
    },
    "dependencies": {
        "execa": "^1.0.0",
        "git-url-parse": "^11.0.1"
    }
}
```

This is on ubuntu 18, with node 11. The same command with the same package.json works fine on macos.

**Comment by bpasero** [comment]
@rberrelleza does it reproduce from a hello world extensions created via `yo code`?

**Comment by umdstu** [comment]
Just found this after hitting the issue myself. During a new extension generation (yo code)- the setup failed because that environment does not have connection to the internet. And because the typings file is only acessible via a github raw URL, rather than a repository like npm, the fetch returns a 404 and fails the rest. 

So while debugging this I decided to re-run the install node ./node_modules/vscode/bin/install which results in the above error. The error message is wrong/misleading, because for starters it's not looking at the package.json file at all, it's looking for an environment variable; `process.env.npm_package_engines_vscode`

This means the installer will also never work unless it's run via the yeoman generator when I can only assume that env variable is defined. Either change the error message, or change the install script to actually use the package.json file (recommended as this would allow it to work outside of the yeoman generator).

**Comment by umdstu** [comment]
@bpasero ^ (edit link not working for me, sorry)

**Comment by rhclayto** [comment]
Running this from the CLI worked for me:
```sh
npm_package_engines_vscode="^1.19.0" node ./node_modules/vscode/bin/install
```

**Comment by octref** [comment]
With the new changes you don't need internet to start new extension: https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest

Just do `yarn add @types/vscode@<VERSION>`, where version can be 1.34.0, 1.35.0, 1.36.0, etc.
