### ISSUE TITLE
Cannot find name 'Thenable'

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode-extension-vscode#21]
I have the vscode.d.ts correctly installed and picked up. But when compiling, I get the error
```
c:/Users/felix/git/opensource/vscode-php/node_modules/vscode/vscode.d.ts(149,11): error TS2304: Cannot find name 'Thenable'.
```
Thenable seems to be defined in typings/es6.d.ts, but there is no `/// <reference path="typings/es6.d.ts">` comment in vscode.d.ts

**Comment by bpasero** [comment]
@felixfbecker I suspect maybe a wrong version of typescript? we now recommend to make typescript a dependency of your extension and then using the tsdk variable to point to the node_modules folder:

"typescript.tsdk": "./node_modules/typescript/lib" // we want to use the TS server from our node_modules folder to control its version

**Comment by felixfbecker** [comment]
I have TS 1.8.9 installed locally as devDep. But I have excluded node_modules with `exclude` from tsconfig.json, as this is suggested in several places. All the other typings from vscode-debugprotocol etc. are picked up fine though, I assume because I are properly referenced through a `///` reference comment. Only vscode.d.ts doesn't have this comment.

**Comment by bpasero** [comment]
@felixfbecker can I get access to the workspace to see this error?

**Comment by felixfbecker** [comment]
To reproduce, make an empty folder with these files:
package.json
```
{
  "devDependencies": {
    "typescript": "^1.8.9",
    "vscode": "^0.11.9"
  },
  "scripts": {
    "postinstall": "node node_modules/vscode/bin/install",
    "compile": "tsc test.ts"
  }
}
```
test.ts
```
import * as vscode from 'vscode';
```
Run `npm install` and then `npm run compile"

**Comment by bpasero** [comment]
@felixfbecker there are a couple of issues with the example, to make it work:
* you will need a typings folder with the vscode-typings.d.ts pointing to the index.d.ts within the vscode module (`/// <reference path="../node_modules/vscode/typings/index.d.ts" />`)
* you will need the tsconfig.json file (see below)
* you will need to run `tsc` and not pass in a file, otherwise `tsconfig.json` gets ignored

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "outDir": "out",
        "noLib": true,
        "sourceMap": true,
        "rootDir": "."
    },
    "exclude": [
        "node_modules"
    ]
}
```

I suggest you look at the generated hello world extension and make the changes necessary to get the compile right, just:
* `npm install -g yo`
* `npm install -g generator-code`
* `yo code`
* pick the typescript extension

**Comment by felixfbecker** [comment]
Looked at it. So I am supposed to make a reference to `/// <reference path="../node_modules/vscode/typings/index.d.ts" />` myself.
